x_api_key = "99f2fb01ab4970a6a3ee"
user_name = "kusch"
user_id = 1104
team_name = "MimicTear"
team_id = 1293
other_team_id = 1294
origin = "https://www.notexponential.com/"
uri = "aip2pgaming/api/index.php"
currentGame = 3704
boardSize = 10
target = 3
color = "black"
timeLimit = 5  # seconds
depthLimit = 5
aggressive = 0.2  # bigger more aggressive, default 1
scoreLevel = 100
debug = False
pruning = True
sorting = True
negativeMax = True
miniMax = False
